import bcrypt from "bcryptjs";

const sampleData = {
  users: [
    {
      name: "User",
      email: "user@user.com",
      password: await bcrypt.hash("123456", 10),
      isAdmin: false,
    },
    {
      name: "Admin",
      email: "admin@admin.com",
      password: await bcrypt.hash("123456", 10),
      isAdmin: true,
    },
  ],
  products: [
    {
      name: "Eyeshadow Palette with Mirror",
      slug: "eyeshadow-palette-with-mirror",
      description:
        "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
      category: "beauty",
      price: 19.99,
      discount: 5,
      rating: 3,
      countInStock: 10,
      brand: "Glamour Beauty",
      sku: "MVCFH27F",
      images: ["/images/eyeshadow-1.png"],
      thumbnail: "/images/eyeshadow-thumbnail.png",
      numReviews: 5,
      isFeatured: false,
    },
    {
      name: "Powder Canister",
      slug: "powder-canister",
      description:
        "The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.",
      category: "beauty",
      price: 14.99,
      discount: 18.14,
      rating: 3.82,
      countInStock: 59,
      brand: "Velvet Touch",
      sku: "9EN8WLT2",
      images: ["/images/powder-canister-1.png"],
      thumbnail: "/images/powder-canister-thumbnail.png",
      numReviews: 6,
      isFeatured: false,
    },
    {
      name: "Red Lipstick",
      slug: "red-lipstick",
      description:
        "The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.",
      category: "beauty",
      price: 12.99,
      discount: 7,
      rating: 2.51,
      countInStock: 68,
      brand: "Chic Cosmetics",
      sku: "O5IF1NTA",
      images: ["/images/red-lipstick-1.png"],
      thumbnail: "/images/red-lipstick-thmbnail.png",
      numReviews: 9,
      isFeatured: true,
    },
    {
      name: "Red Nail Polish",
      slug: "red-nail-polish",
      description:
        "The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.",
      category: "beauty",
      price: 8.99,
      discount: 6.5,
      rating: 3.91,
      countInStock: 71,
      brand: "Nail Couture",
      sku: "YUIIIP4W",
      images: ["/images/red-nail-polish-1.png"],
      thumbnail: "/images/red-nail-polish-thumbnail.png",
      numReviews: 1,
      isFeatured: false,
    },
    {
      name: "Calvin Klein CK One",
      slug: "calvin-klein-ck-one",
      description:
        "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.",
      category: "fragrances",
      price: 49.99,
      discount: 4,
      rating: 4.85,
      countInStock: 17,
      brand: "Calvin Klein",
      sku: "DZM2JQZE",
      images: [
        "/images/calvin-klein-ck-one-1.png",
        "/images/calvin-klein-ck-one-2.png",
        "/images/calvin-klein-ck-one-3.png",
      ],
      thumbnail: "/images/calvin-klein-ck-one-thumbnail.png",
      numReviews: 5,
      isFeatured: true,
    },
    {
      name: "Chanel Coco Noir Eau De",
      slug: "chanel-coco-noir-eau-de",
      description:
        "Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.",
      category: "fragrances",
      price: 129.99,
      discount: 8.5,
      rating: 2.76,
      countInStock: 41,
      brand: "Chanel",
      sku: "K71HBCGS",
      images: [
        "/images/chanel-coco-noir-eau-de-1.png",
        "/images/chanel-coco-noir-eau-de-2.png",
        "/images/chanel-coco-noir-eau-de-3.png",
      ],
      thumbnail: "/images/chanel-coco-noir-eau-de-thumbnail.png",
      numReviews: 11,
      isFeatured: false,
    },
    {
      name: "Dior J'adore",
      slug: "dior-jadore",
      description:
        "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.",
      category: "fragrances",
      price: 89.99,
      rating: 3.31,
      countInStock: 91,
      brand: "Dior",
      sku: "E70NB03B",
      images: [
        "/images/dior-jadore-1.png",
        "/images/dior-jadore-2.png",
        "/images/dior-jadore-3.png",
      ],
      thumbnail: "/images/dior-jadore-thumbnail.png",
      numReviews: 3,
      isFeatured: false,
    },
    {
      name: "Dolce Shine Eau de",
      slug: "dolce-shine-eau-de",
      description:
        "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.",
      category: "fragrances",
      price: 69.99,
      discount: 11.47,
      rating: 3.5,
      countInStock: 23,
      brand: "Dolce & Gabbana",
      sku: "1NBFK980",
      images: [
        "/images/dolce-shine-eau-de-1.png",
        "/images/dolce-shine-eau-de-2.png",
        "/images/dolce-shine-eau-de-3.png",
      ],
      thumbnail: "/images/dolce-shine-eau-de-thumbnail.png",
      numReviews: 7,
      isFeatured: true,
    },
    {
      name: "Gucci Bloom Eau de",
      slug: "gucci-bloom-eau-de",
      description:
        "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent.",
      category: "fragrances",
      price: 79.99,
      discount: 8.9,
      rating: 2.69,
      countInStock: 13,
      brand: "Gucci",
      sku: "FFKZ6HOF",
      images: [
        "/images/gucci-bloom-eau-de-1.png",
        "/images/gucci-bloom-eau-de-2.png",
        "/images/gucci-bloom-eau-de-3.png",
      ],
      thumbnail: "/images/gucci-bloom-eau-de-thumbnail.png",
      numReviews: 3,
      isFeatured: false,
    },
    {
      name: "Annibale Colombo Bed",
      slug: "annibale-colombo-bed",
      description:
        "The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.",
      category: "furniture",
      price: 1899.99,
      discount: 10,
      rating: 4.14,
      countInStock: 2,
      brand: "Annibale Colombo",
      sku: "4KMDTZWF",
      images: [
        "/images/annibale-colombo-bed-1.png",
        "/images/annibale-colombo-bed-2.png",
        "/images/annibale-colombo-bed-3.png",
      ],
      thumbnail: "/images/annibale-colombo-bed-thumbnail.png",
      numReviews: 9,
      isFeatured: true,
    },
    {
      name: "Annibale Colombo Sofa",
      slug: "annibale-colombo-sofa",
      description:
        "The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.",
      category: "furniture",
      price: 2499.99,
      discount: 9,
      rating: 3,
      countInStock: 16,
      brand: "Annibale Colombo",
      sku: "LUU95CQP",
      images: [
        "/images/annibale-colombo-sofa-1.png",
        "/images/annibale-colombo-sofa-2.png",
        "/images/annibale-colombo-sofa-3.png",
      ],
      thumbnail: "/images/annibale-colombo-sofa-thumbnail.png",
      numReviews: 1,
      isFeatured: false,
    },
    {
      name: "Bedside Table African Cherry",
      slug: "bedside-table-african-cherry",
      description:
        "The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.",
      category: "furniture",
      price: 299.99,
      discount: 4,
      rating: 4.5,
      countInStock: 16,
      brand: "Furniture Co.",
      sku: "OWPLTZYX",
      images: [
        "/images/bedside-table-african-cherry-1.png",
        "/images/bedside-table-african-cherry-2.png",
        "/images/bedside-table-african-cherry-3.png",
      ],
      thumbnail: "/images/bedside-table-african-cherry-thumbnail.png",
      numReviews: 3,
      isFeatured: true,
    },
    {
      name: "Knoll Saarinen Executive Conference Chair",
      slug: "knoll-saarinen-executive-conference-chair",
      description:
        "The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.",
      category: "furniture",
      price: 499.99,
      discount: 15.23,
      rating: 4,
      countInStock: 4,
      brand: "Knoll",
      sku: "RKHVJ4FE",
      images: [
        "/images/knoll-saarinen-executive-conference-chair-1.png",
        "/images/knoll-saarinen-executive-conference-chair-2.png",
        "/images/knoll-saarinen-executive-conference-chair-3.png",
      ],
      thumbnail:
        "/images/knoll-saarinen-executive-conference-chair-thumbnail.png",
      numReviews: 1,
      isFeatured: true,
    },
    {
      name: "Wooden Bathroom Sink With Mirror",
      slug: "wooden-bathroom-sink-with-mirror",
      description:
        "The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.",
      category: "furniture",
      price: 799.99,
      discount: 3,
      rating: 5,
      countInStock: 95,
      brand: "Bath Trends",
      sku: "7OLTIEVO",
      images: [
        "/images/wooden-bathroom-sink-with-mirror-1.png",
        "/images/wooden-bathroom-sink-with-mirror-2.png",
        "/images/wooden-bathroom-sink-with-mirror-3.png",
      ],
      thumbnail: "/images/wooden-bathroom-sink-with-mirror-thumbnail.png",
      numReviews: 6,
      isFeatured: true,
    },
    {
      name: "Apple",
      slug: "apple",
      description:
        "Fresh and crisp apples, perfect for snacking or incorporating into various recipes.",
      category: "groceries",
      brand: "Fresh Food",
      price: 1.99,
      rating: 4.5,
      countInStock: 9,
      sku: "QTROUV79",
      images: ["/images/fruit-apple-1.png"],
      thumbnail: "/images/fruit-apple-thumbnail.png",
      numReviews: 2,
      isFeatured: true,
    },
    {
      name: "Beef Steak",
      slug: "beef-steak",
      description:
        "High-quality beef steak, great for grilling or cooking to your preferred level of doneness.",
      category: "groceries",
      brand: "Fresh Food",
      price: 12.99,
      rating: 4,
      countInStock: 96,
      sku: "BWWA2MSO",
      images: ["/images/beef-steak-1.png"],
      thumbnail: "/images/beef-steak-thumbnail.png",
      numReviews: 6,
      isFeatured: false,
    },
    {
      name: "Cat Food",
      slug: "cat-food",
      description:
        "Nutritious cat food formulated to meet the dietary needs of your feline friend.",
      category: "groceries",
      brand: "Fresh Food",
      price: 8.99,
      discount: 4,
      rating: 4.5,
      countInStock: 13,
      sku: "C3F8QN6O",
      images: ["/images/cat-food-1.png"],
      thumbnail: "/images/cat-food-thumbnail.png",
      numReviews: 9,
      isFeatured: true,
    },
    {
      name: "Chicken Meat",
      slug: "chicken-meat",
      description:
        "Fresh and tender chicken meat, suitable for various culinary preparations.",
      category: "groceries",
      brand: "Fresh Food",
      price: 9.99,
      rating: 4.75,
      countInStock: 69,
      sku: "G5YEHW7B",
      images: ["/images/chicken-meat-1.png", "/images/chicken-meat-2.png"],
      thumbnail: "/images/chicken-meat-thumbnail.png",
      numReviews: 5,
      isFeatured: true,
    },
    {
      name: "Cooking Oil",
      slug: "cooking-oil",
      description:
        "Versatile cooking oil suitable for frying, sautéing, and various culinary applications.",
      category: "groceries",
      brand: "Fresh Food",
      price: 4.99,
      discount: 4,
      rating: 4,
      countInStock: 22,
      sku: "Q6ZP1UY8",
      images: ["/images/cooking-oil-1.png"],
      thumbnail: "/images/cooking-oil-thumbnail.png",
      numReviews: 26,
      isFeatured: true,
    },
    {
      name: "Cucumber",
      slug: "cucumber",
      description:
        "Crisp and hydrating cucumbers, ideal for salads, snacks, or as a refreshing side.",
      category: "groceries",
      brand: "Fresh Food",
      price: 1.49,
      discount: 7.44,
      rating: 4.75,
      countInStock: 22,
      sku: "6KGF2K6Z",
      images: ["/images/cucumber-1.png"],
      thumbnail: "/images/cucumber-thumbnail.png",
      numReviews: 15,
      isFeatured: true,
    },
    {
      name: "Dog Food",
      slug: "dog-food",
      description:
        "Specially formulated dog food designed to provide essential nutrients for your canine companion.",
      category: "groceries",
      brand: "Blitz",
      price: 10.99,
      discount: 14,
      rating: 3.5,
      countInStock: 40,
      sku: "A6QRCH37",
      images: ["/images/dog-food-1.png"],
      thumbnail: "/images/dog-food-thumbnail.png",
      numReviews: 4,
      isFeatured: false,
    },
    {
      name: "Eggs",
      slug: "eggs",
      description:
        "Fresh eggs, a versatile ingredient for baking, cooking, or breakfast.",
      category: "groceries",
      brand: "Fresh Food",
      price: 2.99,
      discount: 5.8,
      rating: 4.5,
      countInStock: 10,
      sku: "YA617RI7",
      images: ["/images/eggs-1.png"],
      thumbnail: "/images/eggs-thumbnail.png",
      numReviews: 12,
      isFeatured: false,
    },
    {
      name: "Fish Steak",
      slug: "fish-steak",
      description:
        "Quality fish steak, suitable for grilling, baking, or pan-searing.",
      category: "groceries",
      brand: "Sea Food",
      price: 14.99,
      discount: 7,
      rating: 4.83,
      countInStock: 99,
      sku: "XNIH1MTA",
      images: ["/images/fish-steak-1.png"],
      thumbnail: "/images/fish-steak-thumbnail.png",
      numReviews: 16,
      isFeatured: true,
    },
    {
      name: "Green Bell Pepper",
      slug: "green-bell-pepper",
      description:
        "Fresh and vibrant green bell pepper, perfect for adding color and flavor to your dishes.",
      category: "groceries",
      brand: "Fresh Food",
      price: 1.29,
      discount: 10,
      rating: 4.25,
      countInStock: 89,
      sku: "HU7S7VQ0",
      images: ["/images/green-bell-pepper-1.png"],
      thumbnail: "/images/green-bell-pepper-thumbnail.png",
      numReviews: 13,
      isFeatured: true,
    },
    {
      name: "Green Chili Pepper",
      slug: "green-chili-pepper",
      description:
        "Spicy green chili pepper, ideal for adding heat to your favorite recipes.",
      category: "groceries",
      brand: "Fresh Food",
      price: 0.99,
      discount: 4,
      rating: 4.5,
      countInStock: 80,
      sku: "Y4RM3JCB",
      images: ["/images/green-chili-pepper-1.png"],
      thumbnail: "/images/green-chili-pepper-thumbnail.png",
      numReviews: 12,
      isFeatured: true,
    },
    {
      name: "Honey Jar",
      slug: "honey-jar",
      description:
        "Pure and natural honey in a convenient jar, perfect for sweetening beverages or drizzling over food.",
      category: "groceries",
      brand: "Honey Jar",
      price: 6.99,
      discount: 1.91,
      rating: 4.5,
      countInStock: 25,
      sku: "BTBNIIOU",
      images: ["/images/honey-jar-1.png"],
      thumbnail: "/images/honey-jar-thumbnail.png",
      numReviews: 15,
      isFeatured: true,
    },
    {
      name: "Ice Cream",
      slug: "ice-cream",
      description:
        "Creamy and delicious ice cream, available in various flavors for a delightful treat.",
      category: "groceries",
      brand: "Magnum",
      price: 5.49,
      discount: 7.5,
      rating: 5,
      countInStock: 15,
      sku: "VEZMU1EQ",
      images: [
        "/images/ice-cream-1.png",
        "/images/ice-cream-2.png",
        "/images/ice-cream-3.png",
        "/images/ice-cream-4.png",
      ],
      thumbnail: "/images/ice-cream-thumbnail.png",
      numReviews: 16,
      isFeatured: true,
    },
    {
      name: "Juice",
      slug: "juice",
      description:
        "Refreshing fruit juice, packed with vitamins and great for staying hydrated.",
      category: "groceries",
      brand: "Fresh Food",
      price: 3.99,
      discount: 5,
      rating: 3.5,
      countInStock: 15,
      sku: "M2K19S06",
      images: ["/images/juice-1.png"],
      thumbnail: "/images/juice-thumbnail.png",
      numReviews: 12,
      isFeatured: false,
    },
    {
      name: "Kiwi",
      slug: "kiwi",
      description:
        "Nutrient-rich kiwi, perfect for snacking or adding a tropical twist to your dishes.",
      category: "groceries",
      brand: "Fresh Food",
      price: 2.49,
      discount: 9,
      rating: 4,
      countInStock: 1,
      sku: "0X3NORB9",
      images: ["/images/kiwi-1.png"],
      thumbnail: "/images/kiwi-thumbnail.png",
      numReviews: 26,
      isFeatured: true,
    },
  ],
};

export default sampleData;
